language: node_js
node_js:
    - "12"
script:
    - npm run lint
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/cv-ng-material
    on:
        branch: master
